### ISSUE TITLE
models: id_user -> user_id

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-groups#39]
Shall we go with `user_id` or `id_user` everywhere?

See:
- **user_id**: https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+user_id&type=Code&ref=searchresults
- **id_user**: https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+id_user&type=Code&ref=searchresults

--
cc @inveniosoftware/triagers

**Comment by nharraud** [comment]
As this would imply changing other names too I did some other searchs:
- token:
  - [token_id => 5 results](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+token_id&type=Code&ref=searchresults)
  - [id_token => 0 results](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+id_token&type=Code&ref=searchresults)
- communities:
  - [community_id => 15](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+community_id&type=Code&ref=searchresults)
  - [id_community => 7](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+id_community&type=Code&ref=searchresults)
- session:
  - session_id => 2
  - id_session => 0
- page:
  - page_id => 1
  - id_page => 0
- profile:
  - profile_id => 1
  - id_profile => 0
- record:
  - [record_id => 30](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+record_id&type=Code&ref=searchresults)
  - [id_record => 2](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+id_record&type=Code&ref=searchresults)
- file:
  - [file_id => 19](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+file_id&type=Code&ref=searchresults)
  - [id_file => 0](https://github.com/search?utf8=%E2%9C%93&q=org%3Ainveniosoftware+id_file&type=Code&ref=searchresults)


This goes in the direction of what Google says (and everybody knows Google is always right ;) ):
- [user_id => 22M](https://www.google.com/search?q=user_id&pws=0&gl=us&gws_rd=cr#pws=0&gl=us&q=%22user_id%22)
- [id_user => 1M](https://www.google.com/search?q=%22id_user%22&pws=0&gl=us&gws_rd=cr)

**Comment by kaplun** [comment]
For historical reference: in Invenio 1 `id_foo` was a foreign key to to `foo.id`. `foo_id` was instead a simple way to have an id that was not necessarily an auto-increment primary key.
